export const TILE_SIZE = 32;
export const WORLD_TILES = 64;
export const WORLD_SIZE = TILE_SIZE * WORLD_TILES; // 2048
export const TICK_RATE = 15; // ticks per second
export const ZOOM_MIN = 1.0;
export const ZOOM_MAX = 3.0;
export const ZOOM_STEP = 0.15;
export const ZOOM_LERP = 0.12;
export const CAMERA_ACCELERATION = 0.08;
export const CAMERA_DRAG = 0.003;
export const CAMERA_MAX_SPEED = 0.5;
